### ISSUE TITLE
Document Edit Conflict Resolve

### ISSUE THREAD

**Issue by mike0295** [swsnu/swpp2019-team8#117]
동시에 두명 이상이 같은 document를 수정 할 시, 컨플릭트 해결 위해 optimistic locking을 구현할 예정입니다.
어느정도 머리속에 있긴 하지만 아직 정해지지 않은 디테일들이 있으니 **댓글 부탁**

### 시나리오:
유저 A가 document edit page에서 정보를 바꾸는동안 유저 B가 document edit page에서 정보를 바꾸고 confirm 버튼을 먼저 누른다. 유저 B의 수정은 반영되고, 그 후 유저 A가 confirm 버튼을 누를 시 "그 사이에 다큐먼트 내용이 변했습니다" 하고 알림을 띄운 후, ....... **(미완성)**

### 구현 방법:
유저가 document detail 페이지에서 edit 버튼을 눌러서 document edit page로 넘어가며 현재 document content를 state로 저장 (e.g. prevDocumentContent). (만약 유저가 detail page에서 edit 버튼 누르는 사이에 글이 수정 되었다면 too bad...)

유저가 edit page에서 confirm 버튼 누를 때 다시 한번 document content를 불러와서 (e.g. currDocumentContent), 전에 저장 해두었던 state와 비교한다. 만약 둘이 같다면 유저의 수정을 반영한다. 만약 둘이 다르다면 위 시나리오처럼 진행.

**Comment by mike0295** [comment]
(미완성) 부분을 어떻게 해결할지 의논 필요
페이지 한 쪽에 새로 수정된 글과 어디가 수정됐는지 (하이라이트 해서) 띄우고, 반대쪽엔 수정하던 글/아예 빈칸/수정 된 글 등등 뭐라도 띄울까 하는데...

**Comment by ars-ki-00** [comment]
새로 페이지 하나 만들어서
왼쪽엔 수정하는 부분 오른쪽엔 백엔드에 저장되어 있는 거 해서
그 diff checkr로 다른 부분만 보여줄 수 있으면 좋을거같은디

**Comment by csh3695** [comment]
ㅇㅇ그런듯

2019년 11월 27일 (수) 오전 1:03, dkwanm1 <notifications@github.com>님이 작성:
