### ISSUE TITLE
Upload Photo size limit

### ISSUE THREAD

**Issue by mike0295** [swsnu/swpp2019-team8#129]
사진을 업로드 할 때 파일이 아주 클 시 화면에 담겨지지가 않습니다.

ML과 충돌을 막기 위해 사진을 업로드 하면 바로 크기를 max height/width로 줄인 후, 줄인 버전을 띄워주고 ML에 넣어줘야 할 것 같슴다

**Comment by donghyunlee00** [comment]
해결
