### ISSUE TITLE
alpha test 버그 리포트

### ISSUE THREAD

**Issue by YooYoungJae** [swsnu/swpp2019-team8#140]
team9 의 유영재 입니다.

1. sign in 이후 url 통해 sign up 들어가면 안들어가 져야하는게 맞을듯 합니다.
2. tell-me 는 어떻게 올려봤는데, hear us 는 어떻게 쓰는지 모르겠습니다

**Comment by mike0295** [comment]
2. hear us 청원 진행 설명을 #148 에 올렸습니다! 추가적으로 user-friendliness를 높히기에 주의를 기울 예정입니다!

**Comment by ars-ki-00** [comment]
1. 수정완료했습니다. 감사합니다.
