### ISSUE TITLE
snu mail 입력을 할 수 없습니다ㅠㅠ

### ISSUE THREAD

**Issue by geeglegeegle45** [swsnu/swpp2019-team8#141]
제 snumail id가 minjung0-0@snu.ac.kr 인데 여기서 오류라고 뜨는 것 같습니다ㅠㅠ

**Comment by ars-ki-00** [comment]
죄송합니다 스누메일 아이디에 특수문자가 들어갈 수 있는지 몰랐습니다...
알려주셔서 감사합니다!
