### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by jangsus1** [swsnu/swpp2019-team8#142]
swpp need to be at least 5학점 이라는 청원을 올렸는데 저한테만 보입니다.
서버에는 올라간 듯 한데 다른 유저한테 제대로 spreading 되지 못하는 것 같습니다.

**Comment by mike0295** [comment]
안녕하세요, 청원은 vandalism 방지를 위해 작성 후 링크 배포를 통해 투표수가 하루 안에 5 이상이 되어야 NEW에 뜹니다!
그 전에 확인하고 싶을 시 MINE에서 확인 할 수 있습니다!

**Comment by mike0295** [comment]
#148 이쓔에 청원에 대한 자세한 설명을 올렸습니다!
