### ISSUE TITLE
Petition 문제

### ISSUE THREAD

**Issue by NSYT0607** [swsnu/swpp2019-team8#143]
청원을 작성했는데 New에 안떠요.

**Comment by mike0295** [comment]
안녕하세요, 청원은 작성 후 링크 배포를 통해 투표수가 하루 안에 5 이상이 되어야 NEW에 뜹니다! 
그 전에 확인하고 싶을 시 MINE에서 확인 할 수 있습니다!

**Comment by NSYT0607** [comment]
아하... 감사합니다! 답변으로 달아주신 정보를 제공해주시면 더 좋을 것 같아요.

**Comment by mike0295** [comment]
#148 에 자세한 설명을 올렸습니다! 이 이쓔는 닫겠습니다 :)
