### ISSUE TITLE
Signup 한 직후, 메인페이지로 돌아간 상태에서 렌더 오류

### ISSUE THREAD

**Issue by coiger** [swsnu/swpp2019-team8#144]
상태 : ALUMNUS로 회원가입을 하였습니다.
변화 : 회원가입 후 자동으로 메인페이지로 이동되었습니다.

*보이는 문제
: [렌더링] 메인페이지 상단에 헤더(로고와 사인인/사인업 버튼 있는 부분)가 없습니다.

**Comment by ty8900** [comment]
solved
