### ISSUE TITLE
Sign up 안돼요 / 남이 쓴 글 수정 가능

### ISSUE THREAD

**Issue by ybzzang** [swsnu/swpp2019-team8#145]
![image](https://user-images.githubusercontent.com/32241183/70223799-8a85ad00-178f-11ea-9399-65c9bbe1cfef.png)

**Comment by ars-ki-00** [comment]
혹시 남이 쓴 글 수정가능이 TELL-ME의 경우 말씀하시는 건가요??
죄송합니다 스누메일 아이디에 특수문자가 들어갈 수 있는지 몰랐습니다...
알려주셔서 감사합니다!
