### ISSUE TITLE
(Minor) TELL-ME:기본방침

### ISSUE THREAD

**Issue by kdh9949** [swsnu/swpp2019-team8#149]
문서 내부에

3.3 이용권의 제한

TELL-ME는 규정을 근거로 이용자의 이용권을 제한할 수 있다.

기본적으로 소명권은 제한되지 않는다.

특정한 이용자가 *나무위키* 서버에 많은 부담을 주어 운영상의 문제를 일으키는 경우, 해당 이용자의 이용권을 제한할 수 있다.

여기 고쳐야 되는 것 같습니다! (사소한 거지만..)

**Comment by donghyunlee00** [comment]
제보 감사합니다:)
