### ISSUE TITLE
get_user_by_~~~ backend 구현 관련 

### ISSUE THREAD

**Issue by ars-ki-00** [swsnu/swpp2019-team8#29]
회원 가입 할 때, email, nickname, studentId에 대해서 중복 체크를 할텐데,
그에 해당하는 유저가 있는 경우, 그에 해당하는 유저를 jsonResponse에 담아서 
리턴한다고 생각하면, 만약 해당하는 유저가 없다면 jsonResponse에 무엇을 담아서
리턴해야 한다고 생각하시는지 적어주세요

**Comment by donghyunlee00** [comment]
empty?

**Comment by ars-ki-00** [comment]
비워서 보내면 두 개를 하나의 axios함수를 이용해서 처리가 안 될거 같은데요..?

**Comment by donghyunlee00** [comment]
중복체크 GET_USER_BY_EMAIL, GET_USER_BY_NICKNAME, GET_USER_BY_STUDENT_ID로 하는 거?

**Comment by ars-ki-00** [comment]
옙

**Comment by donghyunlee00** [comment]
그럼 각각 요청 보냈을 때 빈 거 보내면 따로 체크 되는거 아닌가..?

**Comment by ars-ki-00** [comment]
axios에서 if문을 쓰자고?

**Comment by ty8900** [comment]
없으면 없다고 보내면 되지않냐 프론트에서 받아서 처리하면..?

**Comment by ty8900** [comment]
None 같은거

**Comment by mike0295** [comment]
근데 애초부터 중복되는 유저를 리턴 할 이유가 뭐쥬
