### ISSUE TITLE
유저 리덕스, axios 관련 질문

### ISSUE THREAD

**Issue by ars-ki-00** [swsnu/swpp2019-team8#34]
![image](https://user-images.githubusercontent.com/48665265/68010157-33d80f80-fcc7-11e9-93a6-a543a02118b1.png)
뒤에가 잘리기는 했지만 저 4개의 함수가 모두 같은 역할을 하고,
![image](https://user-images.githubusercontent.com/48665265/68010175-42bec200-fcc7-11e9-9596-b48a2448fbdb.png)
![image](https://user-images.githubusercontent.com/48665265/68010186-481c0c80-fcc7-11e9-8706-9224bf67ca9d.png)
마찬가지로 위의 상황에서도 같은 역할을 하는데, 간단하게 getUser로 바꿀려고 하는데 괜찮을까요

**Comment by donghyunlee00** [comment]
ㅇㅇ괜찮은듯

**Comment by ty8900** [comment]
ㅇㅇㅇ괜춘

**Comment by mike0295** [comment]
LGTM ㅎ
verfiyCode 오타는 수정했음 이쓔 닫아도 될듯
