### ISSUE TITLE
TODO: Document create 시 title 중복 불허

### ISSUE THREAD

**Issue by donghyunlee00** [swsnu/swpp2019-team8#45]
_Tell Me_ 에서 document 생성 시 이미 해당 title의 document가 존재하는지 확인 필요

중복 불허

**Comment by ars-ki-00** [comment]
title 유니크로 설정해놓으면 알아서 에러 보낼거같은대...?
엑시오스에서 에러 처리만 해주면 될듯합니다

**Comment by donghyunlee00** [comment]
해결?

**Comment by ty8900** [comment]
이거 에러 나오는데 대신에 프론트에서 제목 중복떄메 포스트안되었다고 알려줘야댐
